name: "ci for nodejs"

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "*"
    # paths:
    #   - "nodejs/**"

jobs:
  dagger:
    runs-on: ubuntu-latest
    defaults:
    steps:
      - name: Change Working Directory
        run: cd nodejs
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
          cache: yarn
      - name: Install
        run: yarn install
      - name: Run Dagger Node.js SDK CI
        run: yarn ci
